// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXIvHlrk_IAhazAi5Iuj1F30K0CB9114',
    appId: '1:964966609672:web:f3c42adf2fd24f205632bd',
    messagingSenderId: '964966609672',
    projectId: 'accident-detector-576d7',
    authDomain: 'accident-detector-576d7.firebaseapp.com',
    storageBucket: 'accident-detector-576d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufNHx7RvPiaCH1Rq7XEpDwjO5R2W8GTg',
    appId: '1:964966609672:android:6b37519d5edf841a5632bd',
    messagingSenderId: '964966609672',
    projectId: 'accident-detector-576d7',
    storageBucket: 'accident-detector-576d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHbxrcfhE7UDd6oxv9moeWx9_swDzxADc',
    appId: '1:964966609672:ios:ba4cc77679a253305632bd',
    messagingSenderId: '964966609672',
    projectId: 'accident-detector-576d7',
    storageBucket: 'accident-detector-576d7.firebasestorage.app',
    iosBundleId: 'com.example.accidentPredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHbxrcfhE7UDd6oxv9moeWx9_swDzxADc',
    appId: '1:964966609672:ios:ba4cc77679a253305632bd',
    messagingSenderId: '964966609672',
    projectId: 'accident-detector-576d7',
    storageBucket: 'accident-detector-576d7.firebasestorage.app',
    iosBundleId: 'com.example.accidentPredictor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIXIvHlrk_IAhazAi5Iuj1F30K0CB9114',
    appId: '1:964966609672:web:e1f6ba408b6253445632bd',
    messagingSenderId: '964966609672',
    projectId: 'accident-detector-576d7',
    authDomain: 'accident-detector-576d7.firebaseapp.com',
    storageBucket: 'accident-detector-576d7.firebasestorage.app',
  );
}
